const places=[
{name:'Praia do Tenório',category:'Praias',icon:'🏖️',desc:'Um destino para incluir no seu dia de praia em Ubatuba.',query:'Praia do Tenório Ubatuba SP',source:'https://turismo.ubatuba.sp.gov.br/praias/praia-do-tenorio/'},
{name:'Praia Grande',category:'Praias',icon:'🌊',desc:'Uma extensa faixa de areia para aproveitar a paisagem e escolher seu cantinho.',query:'Praia Grande Ubatuba SP',source:'https://turismo.ubatuba.sp.gov.br/praias/praia-grande/'},
{name:'Praia da Domingas Dias',category:'Praias',icon:'☀️',desc:'Mais uma opção para descobrir as paisagens do litoral de Ubatuba.',query:'Praia Domingas Dias Ubatuba SP',source:'https://turismo.ubatuba.sp.gov.br/praias/praia-da-domingas-dias/'},
{name:'Orla do Itaguá',category:'Passeios',icon:'🌴',desc:'Inclua a orla em seu roteiro para conhecer outro cenário da cidade.',query:'Orla do Itaguá Ubatuba SP',source:'https://turismo.ubatuba.sp.gov.br/praias/praia-do-itagua/'},
{name:'Projeto Tamar',category:'Passeios',icon:'🐢',desc:'Conheça o centro de visitantes e o trabalho de conservação das tartarugas marinhas.',query:'Projeto Tamar Ubatuba SP',source:'https://projetotamar.org.br/centros_visitantes.php?cod=9'},
{name:'Aquário de Ubatuba',category:'Passeios',icon:'🐠',desc:'Um passeio para conhecer a vida marinha. Consulte ingressos e programação no site.',query:'Aquário de Ubatuba Rua Guarani 859 Ubatuba',source:'https://aquariodeubatuba.com.br/'},
{name:'Restaurante Raízes',category:'Onde comer',icon:'🍽️',desc:'Cozinha caiçara no Itaguá. Veja o cardápio e as informações do restaurante.',query:'Restaurante Raízes Avenida Leovigildo Dias Vieira 1280 Ubatuba',source:'https://www.raizesubatuba.com/'},
{name:'O Rei do Camarão',category:'Onde comer',icon:'🦐',desc:'Uma opção de frutos do mar no Itaguá para conhecer os sabores do litoral.',query:'Rei do Camarão Avenida Leovigildo Dias Vieira 38 Ubatuba',source:'https://restaurantereidocamarao.com.br/'}];
let category='Todos';const esc=s=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const normalize=s=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();function routes(q){return `<a href="https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(q)}" target="_blank" rel="noopener" aria-label="Abrir ${esc(q)} no Google Maps">Google Maps ↗</a><a href="https://www.waze.com/ul?q=${encodeURIComponent(q)}&navigate=yes" target="_blank" rel="noopener" aria-label="Buscar ${esc(q)} no Waze">Waze ↗</a>`}function render(){const q=normalize(document.querySelector('#search').value);const list=places.filter(p=>(category==='Todos'||category===p.category)&&normalize(p.name+' '+p.desc).includes(q));document.querySelector('#places').innerHTML=list.map(p=>`<article class="card"><div class="art" aria-hidden="true"><span>${p.icon}</span></div><div class="card-body"><span class="tag">${p.category}</span><h3>${p.name}</h3><p>${p.desc}</p><div class="links">${routes(p.query)}</div><a class="source" href="${p.source}" target="_blank" rel="noopener">${p.category==='Onde comer'?'Site e cardápio':p.category==='Praias'?'Conhecer a praia':'Informações do local'} ↗</a></div></article>`).join('');document.querySelector('#count').textContent=list.length+' lugares para explorar';document.querySelector('#empty').hidden=!!list.length}document.querySelectorAll('.filter').forEach(b=>b.addEventListener('click',()=>{category=b.dataset.category;document.querySelectorAll('.filter').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));render()}));document.querySelector('#search').addEventListener('input',render);const address='Rua Portuguesa Santista, 481, Estufa II, Ubatuba, SP, CEP 11689-364';document.querySelector('#home-links').innerHTML=routes(address);document.querySelector('#copy').addEventListener('click',async()=>{try{await navigator.clipboard.writeText(address);document.querySelector('#copy-status').textContent='Endereço copiado!'}catch{document.querySelector('#copy-status').textContent='Selecione e copie: '+address}});render();
